### ISSUE TITLE
Defaults for dark background

### ISSUE THREAD

**Issue by flub** [sscherfke/rust-vcprompt#1]
The defaults are very nice but are for light backgrounds.  In the asciinema videos a dark background is used with suitable configuration.  It would be nice to have a simple switch to have nice defaults for dark backgrounds too, e.g. `--bg=light|dark`

**Comment by sscherfke** [comment]
I’m not sure if I understand what you mean. 

Vcprompt just prints ansi color codes and your terminal uses whatever colors you have configured for them. Vcprompt only says “make it blue” and your terminal config defines, what *blue* actually looks like.

**Comment by flub** [comment]
Oh, your terminal translating the colours is a thing terminals are supposed to do these days?  Switching my terminal to use solarized colours rather then the old linux palette indeed makes everything look nice again.  I'll take some getting used too though ;-)
